### ISSUE TITLE
Doesn't enforce timeout on critical notifications

### ISSUE THREAD

**Issue by rockerbacon** [vchlum/notification-timeout#3]
I got this extension because power notifications are left permanently on screen until manually closed but it didn't work. Running the command `notify-send --urgency=critical 'test'` showed that the extension does not enforce the configured timeout on critical notifications.

If this is by design, it would be nice to have an option to enforce a timeout on critical notifications as well.

**Comment by vchlum** [comment]
Thank you @rockerbacon  for pointing this out. The intention was to be able timeout all notifications. So, this is a bug. I will look into it.

**Comment by LeGmask** [comment]
up ?

**Comment by vchlum** [comment]
Fixed.
