### ISSUE TITLE
Notification popups (permanance until clicked option)

### ISSUE THREAD

**Issue by good-unit** [vchlum/notification-timeout#4]
Can you add an option to make all notification popups permanent until clicked away?
If a user gets an important alert and is not looking at the screen for 2 seconds -- they miss it otherwise.

I don't understand why everyone wants 2 second disappearing notifications?

**Comment by vchlum** [comment]
Well, the extension name is "Notification Timeout" and its purpose is to disappear the notification after timeout:-) I do not understand. If you don't want the timeout, uninstall the extension:-)

You can also set the time of notifications on the screen in the settings:
![image](https://user-images.githubusercontent.com/16756616/233904672-06cbe852-9220-47e0-87c9-a21f2ebbf4f6.png)

**Comment by good-unit** [comment]
I appreciate that... and that you responded.

But, wouldn't it be logical to simply add 1 more tiny extra feature (-1 = permanent popup until clicked)?
"Don't timeout" is just the flip side of the coin your extension already deals with. (It's like having dark/light mode options for gui themes).

**Comment by vchlum** [comment]
OK, I added the feature. It will come with the new version (for gnome 45).
