### ISSUE TITLE
Does not work in Ubuntu 23.04 / Gnome 44

### ISSUE THREAD

**Issue by enricojonas** [vchlum/notification-timeout#5]
It seems not to do anything, all notifications stay until manually dismissed.

**Comment by edgan** [comment]
Same for Fedora 38 and Gnome 44.4.

**Comment by vchlum** [comment]
Hi! I can not reproduce this error. For me, it works on Fedora 38 and Gnome 44.4. Also, Ubuntu was tested. Could you please run out `journalctl -f` and while tailing the journal run `notify-send foo bar`. Is there any error in the journal? Also, could you enumerate other extensions you are using? It could be the problem.

**Comment by trodix** [comment]
same for Fedora 37 and Gnome 43.7.

It's working when running `notify-send foo bar` but not when I receive Youtube notifications from google chrome

I guess this is not possible ?
https://www.reddit.com/r/gnome/comments/vb43t2/automatically_dismiss_notifications_from_browser/

**Comment by vchlum** [comment]
Oh, I see. Fixed. It was the same issue as #3. You can now treat all notifications as normal urgency, which is enabled by default. Settable in settings.
