### ISSUE TITLE
Google Chrome notifications not closing after timeout - Release 8

### ISSUE THREAD

**Issue by trodix** [vchlum/notification-timeout#6]
The fix related to issue #5 is not working for Youtube notifications.

I still need to manually close Youtube notifications from google chrome (not tested on Firefox)

![image](https://github.com/vchlum/notification-timeout/assets/34584317/6186de31-66e0-4fda-b645-b175d2080757)

**Comment by vchlum** [comment]
Hi @trodix ! Sorry to hear that. While I am waiting for the YT notification to pop up, could you please try: https://cleverpush.com/en/test-notifications/ ? Does the timeout work on the page? I tested the extension on it.

**Comment by vchlum** [comment]
For me, YT notifications timeout as expected (chrome tested).  Could you please check `journalctl -f` for `notification-timeout`errors?

**Comment by trodix** [comment]
With Google Chrome (tested on version 116) none of the notifications from cleverpush are timeout.

With Firefox, this is working as expected.

I don't have any errors displayed with the journalctl command.

Maybe I can enable some debug logs somehow?

**Comment by vchlum** [comment]
What is your OS and GNome version, please? I will try it in VM.

**Comment by vchlum** [comment]
Please try to disable `Notification Banner Reloaded` or other notification extensions. Log out and in and try again. I think that is the reason.

**Comment by trodix** [comment]
I disabled `Notification Banner Reloaded` and it's working now !

I'll try to see what's interfering with your code in their extension.

So... it looks like I can close this issue. Thanks for the hint :100:
