### ISSUE TITLE
Does not seem to work with GNOME 46

### ISSUE THREAD

**Issue by allentiak** [vchlum/notification-timeout#8]
It worked just fine with GNOME 45...

Version 11 on GNOME 46, installed via extensions.gnome.org

**Comment by vchlum** [comment]
Hi! To me, everytihing works on Gnome 46. I use Arch. What is your distro, please?

Have you enabled 'notifications are always normal' in settings? Try it, please.

I also suggest checking for other extensions. They can interfere with this one. Please, try to disable others.

**Comment by allentiak** [comment]
Hi,

Thanks for the quick reply.

I'm using Debian testing/unstable (currently GNOME 46 is in "experimental", though).

And yes, the first thing I checked is the "notifications are always normal" setting.
And I verified it was enabled (just in case, I also experimented with it disabled).

Below you will find a list of the extensions I have currently enabled.
Do you see any that might be causing problems?

![Screenshot from 2024-04-21 17-13-23](https://github.com/vchlum/notification-timeout/assets/1922297/25e35bd0-6363-4fcf-97f5-199845e31234)

**Comment by allentiak** [comment]
I also tried uninstalling and reinstalling the extension, with no avail.

**Comment by allentiak** [comment]
BTW: I just experimented disabling all the other extensions, with no avail...

**Comment by vchlum** [comment]
Hmm, I installed a fresh debian in my VM and upgraded to unstable, installed this extension, and installed all your extensions. I am not able to reproduce your error. All seems to work properly.

Please, try to run the command `journalctl -f /usr/bin/gnome-shell`, and while this is running call `notify-send foo bar` and check the log for suspicious lines... Or maybe try to search the history of the journal if there are some suspicious lines connected to this extension.

**Comment by allentiak** [comment]
@vchlum Thanks for the testing!
I will have time to see this in detail during next week.
(Just created a reminder for this :)

BTW: Are you make sure that the GNOME version from your VM was indeed 46?
The current GNOME Shell version in unstable is still 45...
https://packages.debian.org/search?keywords=gnome-shell

**Comment by allentiak** [comment]
Forget about my last message: I just tried what you suggested, and the notification timed out as expected!

**Comment by allentiak** [comment]
It seems the problem is specific to one command-line utility I normally use.
https://cljdoc.org/d/lambdaisland/kaocha/1.88.1376/doc/plugin-notifier-desktop-notifications-

I'll continue to explore this and get back to you.
In the meantime, I will leave this open.
Whereas the problem does not seem to be specific to your extension, there is indeed a problem there.

Thanks again for your testing, @vchlum !

**Comment by stephannn** [comment]
Hi,
it seems that I have the same issue with Ubuntu 24.04. 

My journalctl log is following:

```journalctl -f /usr/bin/gnome-shell 
Jul 23 13:55:53 mdl-t14 gnome-shell[25089]: Received faulty track artist metadata from org.mpris.MediaPlayer2.totem; expected an array of strings, got Bruce Springsteen (string)
Jul 23 13:55:53 mdl-t14 gnome-shell[25089]: Received faulty track artist metadata from org.mpris.MediaPlayer2.totem; expected an array of strings, got Bruce Springsteen (string)
Jul 23 13:58:16 mdl-t14 gnome-shell[25089]: Window manager warning: Ping serial 17934025 was reused for window W255, previous use was for window W262.
Jul 23 13:58:46 mdl-t14 gnome-shell[25089]: Window manager warning: Ping serial 17964972 was reused for window W262, previous use was for window W255.
Jul 23 13:58:46 mdl-t14 gnome-shell[25089]: Window manager warning: Ping serial 17964972 was reused for window W262, previous use was for window W255.
Jul 23 13:58:51 mdl-t14 gnome-shell[25089]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Jul 23 13:58:51 mdl-t14 gnome-shell[25089]: Received error from D-Bus search provider org.gnome.Terminal.desktop: Gio.IOErrorEnum: Cannot invoke method; proxy is for the well-known name org.gnome.Terminal without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Jul 23 13:58:54 mdl-t14 gnome-shell[25089]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

The error I get from gnome is:
![image](https://github.com/user-attachments/assets/986e08ae-a19c-4060-b9a2-a77daa58faa7)

I can easily reproduce the error by being on low battery, restart the extension, and unplug the power cable

**Comment by vchlum** [comment]
Sorry @stephannn, this is not a problem with this extension. It seems like a problem with tracker-extract... I casually looked at the tracker-extract code. Not sure but ...try to set the notification timeout to over 5 seconds to avoid this issue. Anyway, I can not solve it here.

**Comment by stephannn** [comment]
Thanks for the explanation. Btw I also have issues with the Dash to Panel. Maybe somehow related to Ubuntu 24.04. Maybe a later release of gnome will fix it. 
Thank you
